//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ComponentTypeId { get; set; }
        public Nullable<int> Equipment_Id { get; set; }
        public Nullable<int> EquipmentType_Id { get; set; }
    
        public virtual ComponentType ComponentType { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
